#!/run/current-system/sw/bin/bash

# Base16 nnn template by Klaasjan Maas
# Generated scheme by Flavours

# 2b2523 - Default Background
# 4e4644 - Lighter Background (Used for status bars, line number and folding marks)
# 706765 - Selection Background
# 938786 - Comments, Invisibles, Line Highlighting
# b5a8a7 - Dark Foreground (Used for status bars)
# d8c9c8 - Default Foreground, Caret, Delimiters, Operators
# ded1d0 - Light Foreground (Not often used)
# e3d9d8 - Light Background (Not often used)
# 85756f - Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
# 7d7770 - Integers, Boolean, Constants, XML Attributes, Markup Link Url
# b47b73 - Classes, Markup Bold, Search Text Background
# ad7170 - Strings, Inherited Class, Markup Code, Diff Inserted
# 787875 - Support, Regular Expressions, Escape Characters, Markup Quotes
# 787878 - Functions, Methods, Attribute IDs, Headings
# 797878 - Keywords, Storage, Selector, Markup Italic, Diff Changed
# 7a7874 - Deprecated, Opening/Closing Embedded Language Tags


# Set a distinct color for each tab (by default all are blue)
# example (with optional fallback in base-8):
tab1="b47b73"
tab2="85756f"
tab3="797878"
tab4="7a7874"

# file-specific colors
blk="ad7170"
chr="ad7170"
dir="2b2523"
exe="ded1d0"
reg="e3d9d8"
hardlink="ded1d0"
symlink="b5a8a7"
missing="85756f"
orphan="7d7770"
fifo="ded1d0"
sock="ad7170"
other="ded1d0"
