
# Commands go through bash
shell = "zsh -c '{}'"

# Sway supports the default '#' comments, so it can be ommited
# 'rewrite' is also ommited, as it defaults to false
[[items]]
file = "~/.config/sway/colorscheme"
template = "sway"
subtemplate = "colors"
hook = "swaymsg reload"
rewrite = true
# Swaymsg reload temporarily freezes input, so it's marked as not light
light = false

[[item]]
file = "~/.config/waybar/colors.css"
template = "waybar"
hook = "pkill -SIGUSR2 waybar"
rewrite = true

[[item]]
file = "~/.config/rofi/themes/colors.rasi"
template = "rofi"
subtemplate = "custom"
rewrite = true

[[item]]
file = "~/.config/kitty/kitty.conf"
template = "kitty"
subtemplate = "default"
rewrite = false
start= "# Start flavours"
end = "# End flavours"
hook = "kill -SIGUSR1 $(pgrep kitty)"

[[item]]
file = "~/.config/zathura/zathurarc"
template = "zathura"
subtemplate = "recolor"
rewrite = false
start= "/* Start flavours */"
end = "/* End flavours */"

[[item]]
file = "~/.config/nnn/colors"
template = "nnn"
subtemplate = "custom"
rewrite = true
hook = "bash $HOME/.config/nnn/convert_colors.sh"

